// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "string",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": [],
            "Access-Control-Allow-Credentials": [],
            "Access-Control-Allow-Origin": [],
            "Access-Control-Allow-Headers": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": [],
            "Access-Control-Allow-Credentials": [],
            "Access-Control-Allow-Origin": [],
            "Access-Control-Allow-Headers": []
          }
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        }
      },
      "required": [
        "id",
        "price",
        "title",
        "description"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "Access-Control-Allow-Credentials": {
      "type": "apiKey",
      "name": "Access-Control-Allow-Credentials",
      "in": "header"
    },
    "Access-Control-Allow-Origin": {
      "type": "apiKey",
      "name": "Access-Control-Allow-Origin",
      "in": "header"
    },
    "Access-Control-Allow-Headers": {
      "type": "apiKey",
      "name": "Access-Control-Allow-Headers",
      "in": "header"
    }
  },
  "basePath": "/dev",
  "schemes": [
    "http",
    "https",
    "ws",
    "wss"
  ]
};